### ISSUE TITLE
Plans for 1.15.2?

### ISSUE THREAD

**Issue by Flexz9** [AtomicBlom/WeirdingGadget#22]
Hi,

I've seen there is activity a week ago to port to 1.16.
Is there a chance of a 1.15.2 port as well?

Got a server going with some friends but the base is getting to big to load it by yourself and if we can load certain area's based on who's online that would be amazing! And if we can set like a 1day or less to unload that would be nice.

We don't want to load to much area all the time and this mod looks to do just that.

And if I would attempt it by myself, without modding experience, would it be possible?

**Comment by AtomicBlom** [comment]
Hmm, maybe. The main reason why it wasn't ported past 1.12.2 for the longest time was because Mojang made BIG changes to how chunks are kept alive. If it's the same between 1.16 and 1.15 a port shouldn't be too hard.

I can promise I'll take a look at it, but I won't promise I'll be able to deliver it if it's too much effort to be worth the cost of maintaining it.
